<?php
if ( ! defined( 'ABSPATH' ) ) exit;
$strings = Control_I18n::get_all();
?>

<div id="kiosk-app-root" style="direction:rtl; font-family:'Rubik', sans-serif; position:fixed; top:0; left:0; width:100vw; height:100vh; background:#f8fafc; z-index:999999; display:flex; flex-direction:column; box-sizing:border-box; overflow:hidden;">

    <!-- Immersive Header -->
    <div id="k-header" style="background:var(--control-primary); padding:0 40px; color:#fff; display:flex; justify-content:space-between; align-items:center; flex-shrink:0; height: 75px; box-shadow: 0 4px 12px rgba(0,0,0,0.1);">
        <div style="display:flex; align-items:center; gap:15px;">
            <div style="background:rgba(255,255,255,0.1); padding:8px; border-radius:12px;">
                <span class="dashicons dashicons-id-alt" style="color:var(--control-accent); font-size:24px; width:24px; height:24px;"></span>
            </div>
            <h3 id="k-header-title" style="margin:0; font-size:1.2rem; color:#fff; font-weight:800; letter-spacing:-0.5px;"><?php echo Control_I18n::t('registration_title'); ?></h3>
        </div>

        <div id="k-dots-container" style="display:flex; gap:10px; align-items:center; background:rgba(0,0,0,0.2); padding:10px 20px; border-radius:30px;">
            <!-- Generated by JS -->
        </div>

        <div style="display:flex; gap:15px; align-items:center;">
            <div style="display:flex; background:rgba(255,255,255,0.1); border-radius:10px; padding:4px;">
                <button type="button" onclick="setKLang('ar')" class="lang-btn" id="btn-ar">AR</button>
                <button type="button" onclick="setKLang('en')" class="lang-btn" id="btn-en">EN</button>
            </div>
        </div>
    </div>

    <!-- Step Progress Header (Internal) -->
    <div id="k-step-header" style="background:#fff; border-bottom:1px solid #e2e8f0; padding:15px 40px; display:flex; justify-content:space-between; align-items:center; flex-shrink:0;">
        <div style="display:flex; align-items:center; gap:12px;">
            <span id="k-current-step-num" style="background:var(--control-accent); color:var(--control-primary); width:32px; height:32px; border-radius:50%; display:flex; align-items:center; justify-content:center; font-weight:800; font-size:0.9rem;">1</span>
            <h4 id="k-current-step-title" style="margin:0; font-weight:800; color:var(--control-primary); font-size:1rem;">---</h4>
        </div>
        <div style="color:var(--control-muted); font-weight:700; font-size:0.9rem;">
            <span id="k-step-progress-text">Step 1 of 15</span>
        </div>
    </div>

    <!-- Main Content Area (Screen-Fitted) -->
    <form id="kiosk-form" style="flex:1; display:flex; flex-direction:column; overflow:hidden; position:relative;">
        <input type="hidden" name="k_lang" id="k-selected-lang" value="ar">
        <input type="hidden" name="full_name" id="k-full-name-concat">
        <input type="hidden" name="id" value="<?php echo $resume_id; ?>">

        <div id="k-step-container" style="flex:1; display:flex; align-items:flex-start; justify-content:center; padding:40px; box-sizing:border-box; overflow-y:auto;">
            <!-- Sub-steps rendered here -->
            <div id="k-step-content" style="width:100%; max-width:900px; transform: translateY(0); transition: 0.3s opacity;">
                <!-- Inner fields -->
            </div>
        </div>

        <!-- Sticky Footer -->
        <div id="k-footer" style="padding:0 40px; background:#fff; border-top:2px solid #f1f5f9; display:flex; justify-content:space-between; align-items:center; height: 110px; flex-shrink:0; box-shadow: 0 -4px 20px rgba(0,0,0,0.05);">

            <!-- Left Side: Admin Identity (Only for Staff) -->
            <div id="k-admin-panel" style="display:<?php echo $is_staff ? 'flex' : 'none'; ?>; align-items:center; gap:15px; background:#f8fafc; padding:12px 25px; border-radius:18px; border:1px solid #e2e8f0;">
                <div style="width:50px; height:50px; border-radius:50%; background:var(--control-primary); color:#fff; display:flex; align-items:center; justify-content:center; font-weight:800; border:2px solid #fff; box-shadow:0 4px 12px rgba(0,0,0,0.1); overflow:hidden;">
                    <?php
                        $user = Control_Auth::current_user();
                        $staff_data = null;
                        if ($is_staff && is_numeric($user->id)) {
                            $staff_data = $wpdb->get_row($wpdb->prepare("SELECT profile_image, role FROM {$wpdb->prefix}control_staff WHERE id = %d", $user->id));
                        }

                        if (!empty($staff_data->profile_image)): ?>
                            <img src="<?php echo esc_url($staff_data->profile_image); ?>" style="width:100%; height:100%; object-fit:cover;">
                        <?php else: ?>
                            <?php
                                $initial = 'A';
                                if (!empty($user->first_name)) $initial = substr($user->first_name, 0, 1);
                                else if (!empty($user->name)) $initial = substr($user->name, 0, 1);
                                echo strtoupper($initial);
                            ?>
                        <?php endif; ?>
                </div>
                <div style="line-height:1.3;">
                    <div style="font-size:0.75rem; color:var(--control-muted); font-weight:700; text-transform:uppercase; letter-spacing:0.5px;"><?php echo Control_I18n::t('welcome_user'); ?></div>
                    <div style="font-weight:800; color:var(--control-primary); font-size:1.05rem;"><?php echo esc_html($user->name); ?></div>
                    <div style="font-size:0.75rem; color:var(--control-accent); font-weight:900; background:rgba(212,175,55,0.1); padding:2px 8px; border-radius:6px; display:inline-block; margin-top:2px;">
                        <?php
                            if ($staff_data && !empty($staff_data->role)) {
                                $role_labels = Control_Auth::get_roles();
                                echo esc_html($role_labels[$staff_data->role] ?? 'Staff');
                            } else {
                                echo 'Administrator';
                            }
                        ?>
                    </div>
                </div>
            </div>

            <div style="flex:1;"></div>

            <!-- Right Side: Navigation -->
            <div style="display:flex; gap:15px; align-items:center;">
                <button type="button" id="k-prev" onclick="prevKStep()" class="k-btn-secondary" style="display:none; min-width:140px;"><?php echo Control_I18n::t('prev'); ?></button>
                <button type="button" id="k-next" onclick="nextKStep()" class="k-btn-primary" style="min-width:160px; box-shadow: 0 4px 12px var(--control-primary-soft);"><?php echo Control_I18n::t('next'); ?></button>
                <button type="submit" id="k-submit" style="display:none; min-width:200px; background:var(--control-accent); color:var(--control-primary);" class="k-btn-primary"><?php echo Control_I18n::t('save'); ?></button>
            </div>
        </div>
    </form>

    <div id="kiosk-success" style="display:none; flex:1; flex-direction:column; align-items:center; justify-content:center; padding:40px; text-align:center; background:#fff;">
        <div style="width:100px; height:100px; background:#ecfdf5; border-radius:50%; display:flex; align-items:center; justify-content:center; margin-bottom:30px; color:#10b981;">
            <span class="dashicons dashicons-yes-alt" style="font-size:60px; width:60px; height:60px;"></span>
        </div>
        <h1 style="font-weight:800; color:#065f46; font-size:2.2rem;" data-t="success_title"><?php echo Control_I18n::t('success_title'); ?></h1>
        <p style="font-size:1.2rem; color:#475569; margin-bottom:40px;" data-t="success_desc"><?php echo Control_I18n::t('success_desc'); ?></p>
        <button onclick="location.href='<?php echo home_url(); ?>'" class="k-btn-primary" style="padding:15px 60px;" data-t="finish_btn"><?php echo Control_I18n::t('finish_btn'); ?></button>
    </div>
</div>

<style>
#kiosk-app-root * { box-sizing: border-box; }
.lang-btn { background:none; border:none; color:rgba(255,255,255,0.5); cursor:pointer; font-size:0.75rem; font-weight:800; padding:6px 12px; border-radius:8px; transition:0.3s; }
.lang-btn.active { background:#fff; color:var(--control-primary); box-shadow:0 2px 6px rgba(0,0,0,0.1); }

.k-dot { width: 8px; height: 8px; border-radius: 50%; background: rgba(255,255,255,0.2); transition: 0.4s; }
.k-dot.active { background: var(--control-accent); transform: scale(1.4); }
.k-dot.completed { background: #fff; }

.k-btn-primary { background:var(--control-primary); color:#fff; border:none; padding:16px 35px; font-size:1.05rem; border-radius:14px; font-weight:800; cursor:pointer; transition: 0.3s; display:flex; align-items:center; justify-content:center; gap:10px; }
.k-btn-secondary { background:#fff; color:#475569; border:2px solid #e2e8f0; padding:16px 35px; font-size:1.05rem; border-radius:14px; font-weight:800; cursor:pointer; transition: 0.3s; }
.k-btn-primary:hover { transform: translateY(-2px); filter: brightness(1.1); }
.k-btn-secondary:hover { background: #f8fafc; border-color: #cbd5e1; }

.wiz-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 30px; }
.wiz-field { margin-bottom: 0; }
.wiz-field label { display: block; font-size: 0.85rem; font-weight: 800; color: #64748b; margin-bottom: 8px; text-transform: uppercase; }
.wiz-field input, .wiz-field select, .wiz-field textarea { width: 100%; padding: 14px 18px; border-radius: 12px; border: 2px solid #e2e8f0; font-size: 1rem; background:#fff; transition:0.3s; color: #1e293b; font-family: inherit; }
.wiz-field input:focus { border-color: var(--control-primary); outline:none; }

@media (max-width: 768px) {
    .wiz-grid { grid-template-columns: 1fr; gap: 15px; }
    #k-header { padding: 10px 20px; }
    #k-footer { padding: 15px 30px; }
    #k-step-container { padding: 20px; }
}
</style>

<script>
const kStrings = <?php echo json_encode($strings); ?>;
const isStaff = <?php echo $is_staff ? 'true' : 'false'; ?>;
const resumeData = <?php echo json_encode($resume_data); ?>;

// Comprehensive Step Tree for Unified Flow
const stepTree = [
    { id: '1.1', phase: 1, title: 'identity_basic', fields: ['name_first', 'name_second', 'name_last'] },
    { id: '1.2', phase: 1, title: 'dob_gender', fields: ['dob', 'gender'] },
    { id: '1.3', phase: 1, title: 'nationality_residence', fields: ['nationality', 'country_residence', 'city_residence', 'national_id'] },

    { id: '2.1', phase: 2, title: 'guardian_identity', fields: ['guardian_name', 'guardian_relationship', 'guardian_id'] },
    { id: '2.2', phase: 2, title: 'guardian_contact', fields: ['father_phone', 'email'] },
    { id: '2.3', phase: 2, title: 'address_emergency', fields: ['address', 'emergency_contact', 'blood_type'] },

    { id: '3.1', phase: 3, title: 'medical_history_prev', fields: ['diag_prev', 'diag_prev_details', 'prev_rehab_centers'] },
    { id: '3.2', phase: 3, title: 'medical_history_cond', fields: ['chronic_conditions', 'current_medications'] },
    { id: '3.3', phase: 3, title: 'medical_history_delay', fields: ['motor_delay', 'speech_delay', 'sleep_issues', 'feeding_issues'] },

    { id: '4.1', phase: 4, title: 'functional_social', fields: ['eval_attention', 'eval_name_response', 'eval_eye_contact', 'eval_social'] },
    { id: '4.2', phase: 4, title: 'functional_behavior', fields: ['eval_tantrums', 'eval_instructions', 'eval_activity_level'] },
    { id: '4.3', phase: 4, title: 'functional_skills', fields: ['eval_independence', 'eval_language', 'eval_anxiety', 'intake_reason'] }
];

if (isStaff) {
    stepTree.push(
        { id: '5.1', phase: 5, title: 'internal_analysis_1', fields: ['case_classification', 'priority_level', 'suggested_pathway'] },
        { id: '5.2', phase: 5, title: 'internal_analysis_2', fields: ['final_decision', 'temp_id', 'assigned_specialists', 'internal_notes'] },
        { id: '6.1', phase: 6, title: 'financial_setup', fields: ['registration_cost', 'payment_model', 'billing_type', 'amount_per_cycle'] },
        { id: '7.1', phase: 7, title: 'final_activation', fields: ['permanent_id', 'case_status', 'activate_account'] }
    );
}

let currentStepIdx = 0;

// Resume logic: If resumeData exists, we find the first empty phase or start at Phase 5
if (resumeData) {
    if (resumeData.intake_status === 'pending') {
        currentStepIdx = stepTree.findIndex(s => s.phase === 5);
    }
}

const optionData = {
    gender: { ar: [{v:'male', t:'ذكر (Male)'}, {v:'female', t:'أنثى (Female)'}], en: [{v:'male', t:'Male'}, {v:'female', t:'Female'}] },
    nationality: {
        ar: [{v:'SA', t:'المملكة العربية السعودية'}, {v:'AE', t:'الإمارات العربية المتحدة'}, {v:'EG', t:'جمهورية مصر العربية'}, {v:'KW', t:'الكويت'}, {v:'QA', t:'قطر'}, {v:'BH', t:'البحرين'}, {v:'OM', t:'سلطنة عمان'}, {v:'JO', t:'الأردن'}, {v:'other', t:'جنسيات أخرى'}],
        en: [{v:'SA', t:'Saudi Arabia'}, {v:'AE', t:'United Arab Emirates'}, {v:'EG', t:'Egypt'}, {v:'KW', t:'Kuwait'}, {v:'QA', t:'Qatar'}, {v:'BH', t:'Bahrain'}, {v:'OM', t:'Oman'}, {v:'JO', t:'Jordan'}, {v:'other', t:'Other'}]
    },
    relationship: {
        ar: [{v:'father', t:'الأب (Father)'}, {v:'mother', t:'الأم (Mother)'}, {v:'relative', t:'قريب من الدرجة الأولى'}, {v:'legal', t:'ولي أمر شرعي'}],
        en: [{v:'father', t:'Father'}, {v:'mother', t:'Mother'}, {v:'relative', t:'First-degree Relative'}, {v:'legal', t:'Legal Guardian'}]
    },
    blood_type: { ar: [{v:'', t:'-'}, {v:'A+', t:'A+'}, {v:'A-', t:'A-'}, {v:'B+', t:'B+'}, {v:'B-', t:'B-'}, {v:'AB+', t:'AB+'}, {v:'AB-', t:'AB-'}, {v:'O+', t:'O+'}, {v:'O-', t:'O-'}], en: [{v:'', t:'-'}, {v:'A+', t:'A+'}, {v:'A-', t:'A-'}, {v:'B+', t:'B+'}, {v:'B-', t:'B-'}, {v:'AB+', t:'AB+'}, {v:'AB-', t:'AB-'}, {v:'O+', t:'O+'}, {v:'O-', t:'O-'}] },
    boolean: { ar: [{v:'no', t:'لا (No)'}, {v:'yes', t:'نعم (Yes)'}], en: [{v:'no', t:'No'}, {v:'yes', t:'Yes'}] },
    social: { ar: [{v:'positive', t:'تفاعل جيد (Good)'}, {v:'limited', t:'تفاعل محدود (Average)'}, {v:'isolated', t:'ضعيف / منعزل (Poor)'}], en: [{v:'positive', t:'Good'}, {v:'limited', t:'Average'}, {v:'isolated', t:'Poor'}] },
    language: { ar: [{v:'non_verbal', t:'غير ناطق (Non-verbal)'}, {v:'words', t:'كلمات مفردة (Words)'}, {v:'sentences', t:'جمل قصيرة (Sentences)'}], en: [{v:'non_verbal', t:'Non-verbal'}, {v:'words', t:'Single Words'}, {v:'sentences', t:'Short Sentences'}] },
    classification: { ar: [{v:'normal', t:'حالة طبيعية (Normal)'}, {v:'possible_delay', t:'تأخر نمائي محتمل'}, {v:'needs_evaluation', t:'يحتاج تقييم فني'}, {v:'needs_intervention', t:'يحتاج تدخل عاجل'}], en: [{v:'normal', t:'Normal'}, {v:'possible_delay', t:'Possible Delay'}, {v:'needs_evaluation', t:'Needs Technical Evaluation'}, {v:'needs_intervention', t:'Needs Urgent Intervention'}] },
    priority: { ar: [{v:'normal', t:'طبيعية (Normal)'}, {v:'urgent', t:'عاجلة (Urgent)'}, {v:'critical', t:'حالة حرجة (Critical)'}], en: [{v:'normal', t:'Normal'}, {v:'urgent', t:'Urgent'}, {v:'critical', t:'Critical'}] },
    pathway: { ar: [{v:'consultation', t:'جلسة استشارية'}, {v:'assessment', t:'تقييم شامل'}, {v:'rehab_program', t:'برنامج تأهيلي مكثف'}], en: [{v:'consultation', t:'Consultation'}, {v:'assessment', t:'Comprehensive Assessment'}, {v:'rehab_program', t:'Intensive Rehab Program'}] },
    decision: { ar: [{v:'pre_acceptance', t:'قبول مبدئي (Pre-acceptance)'}, {v:'rejected', t:'مرفوض (Rejected)'}, {v:'closed', t:'ملف مغلق (Closed)'}], en: [{v:'pre_acceptance', t:'Pre-acceptance'}, {v:'rejected', t:'Rejected'}, {v:'closed', t:'Closed'}] },
    status: { ar: [{v:'active', t:'ملف نشط بالنظام'}, {v:'evaluation_only', t:'تقييم فقط'}, {v:'waiting_list', t:'قائمة الانتظار'}, {v:'completed', t:'أتم التأهيل (Completed)'}, {v:'closed', t:'ملف مغلق'}], en: [{v:'active', t:'Active in System'}, {v:'evaluation_only', t:'Evaluation Only'}, {v:'waiting_list', t:'Waiting List'}, {v:'completed', t:'Completed Rehabilitation'}, {v:'closed', t:'Closed File'}] },
    payment_model: { ar: [{v:'one_time', t:'دفع لمرة واحدة'}, {v:'daily', t:'دفع يومي'}, {v:'weekly', t:'اشتراك أسبوعي'}, {v:'monthly', t:'اشتراك شهري'}], en: [{v:'one_time', t:'One-time fee'}, {v:'daily', t:'Daily'}, {v:'weekly', t:'Weekly'}, {v:'monthly', t:'Monthly'}] },
    billing_type: { ar: [{v:'session_based', t:'حسب الجلسات'}, {v:'subscription_based', t:'نظام اشتراك'}], en: [{v:'session_based', t:'Session-based'}, {v:'subscription_based', t:'Subscription-based'}] }
};

function renderStep() {
    const $ = jQuery;
    const step = stepTree[currentStepIdx];
    const lang = $('#k-selected-lang').val();
    const s = kStrings[lang];

    // Auto-scroll to top when step changes
    $('#k-step-container').animate({ scrollTop: 0 }, 200);

    $('#k-step-content').css('opacity', 0);

    setTimeout(() => {
        let html = `<h2 style="color:var(--control-primary); font-weight:800; margin-bottom:35px; text-align:center;">${s[step.title] || step.title}</h2>`;
        html += `<div class="wiz-grid">`;

        step.fields.forEach(f => {
            const val = resumeData ? (resumeData[f] || '') : '';
            html += `<div class="wiz-field">`;
            html += `<label>${s[f] || f}</label>`;

            if (['gender', 'nationality', 'guardian_relationship', 'blood_type', 'diag_prev', 'prev_rehab_centers', 'motor_delay', 'speech_delay', 'sleep_issues', 'feeding_issues', 'eval_social', 'eval_language', 'case_classification', 'priority_level', 'suggested_pathway', 'final_decision', 'case_status', 'payment_model', 'billing_type'].includes(f)) {
                let source = f;
                if (['diag_prev', 'prev_rehab_centers', 'motor_delay', 'speech_delay', 'sleep_issues', 'feeding_issues'].includes(f)) source = 'boolean';
                if (f === 'eval_social') source = 'social';
                if (f === 'eval_language') source = 'language';
                if (f === 'guardian_relationship') source = 'relationship';
                if (f === 'case_classification') source = 'classification';
                if (f === 'priority_level') source = 'priority';
                if (f === 'suggested_pathway') source = 'pathway';
                if (f === 'final_decision') source = 'decision';
                if (f === 'case_status') source = 'status';

                html += `<select name="${f}">`;
                (optionData[source][lang] || []).forEach(opt => {
                    const selected = val == opt.v ? 'selected' : '';
                    html += `<option value="${opt.v}" ${selected}>${opt.t}</option>`;
                });
                html += `</select>`;
            } else if (['intake_reason', 'initial_behavioral_observation', 'initial_diagnosis', 'internal_notes', 'assigned_specialists'].includes(f)) {
                html += `<textarea name="${f}" rows="3">${val}</textarea>`;
            } else if (f === 'activate_account') {
                html += `<label style="display:flex; align-items:center; gap:10px; cursor:pointer; background:#f8fafc; padding:15px; border-radius:12px; border:2px solid #e2e8f0;">
                            <input type="checkbox" name="activate_account" value="1" ${val ? 'checked' : ''}>
                            <span style="font-size:0.9rem; color:var(--control-primary);">${s.account_activation}</span>
                         </label>`;
            } else {
                let type = 'text';
                if (f === 'dob') type = 'date';
                else if (f === 'email') type = 'email';
                else if (f === 'father_phone') type = 'tel';
                else if (['registration_cost', 'amount_per_cycle'].includes(f)) type = 'number';

                const required = ['name_first', 'name_second', 'name_last', 'dob', 'guardian_name', 'father_phone'].includes(f) ? 'required' : '';
                html += `<input type="${type}" name="${f}" value="${val}" ${required} step="0.01">`;
            }
            html += `</div>`;
        });

        html += `</div>`;

        $('#k-step-content').html(html).css('opacity', 1);
        updateKUI();
    }, 150);
}

function nextKStep() {
    if (validateStep()) {
        if (currentStepIdx < stepTree.length - 1) {
            currentStepIdx++;
            renderStep();
        }
    }
}

function prevKStep() {
    if (currentStepIdx > 0) {
        currentStepIdx--;
        renderStep();
    }
}

function updateKUI() {
    const $ = jQuery;
    const lang = $('#k-selected-lang').val();
    const s = kStrings[lang];
    const step = stepTree[currentStepIdx];

    $('#k-prev').toggle(currentStepIdx > 0).text(s.prev);
    $('#k-next').toggle(currentStepIdx < stepTree.length - 1).text(s.next);
    $('#k-submit').toggle(currentStepIdx === stepTree.length - 1).text(s.save);

    // Update Top Step Header
    $('#k-current-step-num').text(currentStepIdx + 1);
    $('#k-current-step-title').text(s[step.title] || step.title);
    $('#k-step-progress-text').text(`${lang === 'ar' ? 'الخطوة' : 'Step'} ${currentStepIdx + 1} / ${stepTree.length}`);

    // Generate Dots
    let dotsHtml = '';
    stepTree.forEach((step, idx) => {
        let status = '';
        if (idx === currentStepIdx) status = 'active';
        else if (idx < currentStepIdx) status = 'completed';
        dotsHtml += `<div class="k-dot ${status}" title="Step ${step.id}"></div>`;
    });
    $('#k-dots-container').html(dotsHtml);

    // Smooth entry for fields
    $('.wiz-field').each(function(i) {
        $(this).css({ 'opacity': 0, 'transform': 'translateY(10px)' });
        setTimeout(() => {
            $(this).animate({ 'opacity': 1, 'transform': 'translateY(0)' }, 300);
            $(this).css('transform', 'none'); // Fix transform stickiness
        }, i * 50);
    });
}

function validateStep() {
    let valid = true;
    jQuery('#k-step-content [required]').each(function() {
        if (!jQuery(this).val()) { jQuery(this).css('border-color', '#ef4444'); valid = false; }
        else { jQuery(this).css('border-color', ''); }
    });
    return valid;
}

function setKLang(lang) {
    const $ = jQuery;
    $('#k-selected-lang').val(lang);
    $('.lang-link').removeClass('active');
    $(`#btn-${lang}`).addClass('active');
    $('#kiosk-app-root').css('direction', lang === 'ar' ? 'rtl' : 'ltr');
    renderStep();
}

jQuery(document).ready(function($) {
    setKLang('ar');

    $('#kiosk-form').on('submit', function(e) {
        e.preventDefault();
        const $btn = $('#k-submit'); $btn.prop('disabled', true).text('...');

        // Auto-concat full name
        const f = $('[name="name_first"]').val() || '';
        const s = $('[name="name_second"]').val() || '';
        const l = $('[name="name_last"]').val() || '';
        $('#k-full-name-concat').val(`${f} ${s} ${l}`.trim());

        const ajaxAction = isStaff ? 'control_save_patient' : 'control_submit_kiosk_registration';

        $.post(control_ajax.ajax_url, $(this).serialize() + '&action=' + ajaxAction + '&nonce=' + control_ajax.nonce, (res) => {
            if (res.success) {
                $('#kiosk-form, #k-header, #k-step-header').hide();
                $('#kiosk-success').css('display', 'flex');

                // If it was an edit/admin action, maybe show a different message or redirect back after 3s
                if (isStaff) {
                    setTimeout(() => {
                        window.location.href = '<?php echo add_query_arg("control_view", "pediatric_records", home_url()); ?>';
                    }, 3000);
                }
            } else {
                const msg = (typeof res.data === 'string') ? res.data : (res.data.message || 'Error occurred');
                alert(msg);
                $btn.prop('disabled', false).text(kStrings[$('#k-selected-lang').val()].save);
            }
        });
    });
});
</script>
