<?php
if ( ! defined( 'ABSPATH' ) ) exit;
$strings = Control_I18n::get_all();
?>

<div id="kiosk-app-root" style="direction:rtl; font-family:'Rubik', sans-serif; position:fixed; top:0; left:0; width:100vw; height:100vh; background:#fff; z-index:999999; display:flex; flex-direction:column; box-sizing:border-box; overflow:hidden;">

    <!-- Immersive Header -->
    <div id="k-header" style="background:var(--control-primary); padding:15px 40px; color:#fff; display:flex; justify-content:space-between; align-items:center; flex-shrink:0; height: 70px;">
        <h3 id="k-header-title" style="margin:0; font-size:1.1rem; color:#fff; font-weight:800;"><?php echo Control_I18n::t('registration_title'); ?></h3>

        <div id="k-dots-container" style="display:flex; gap:8px; align-items:center;">
            <!-- Generated by JS -->
        </div>

        <div style="display:flex; gap:20px; align-items:center;">
            <button type="button" onclick="setKLang('ar')" class="lang-link" id="btn-ar">العربية</button>
            <div style="width:1px; height:15px; background:rgba(255,255,255,0.3);"></div>
            <button type="button" onclick="setKLang('en')" class="lang-link" id="btn-en">English</button>
        </div>
    </div>

    <!-- Main Content Area (Screen-Fitted) -->
    <form id="kiosk-form" style="flex:1; display:flex; flex-direction:column; overflow:hidden; position:relative;">
        <input type="hidden" name="k_lang" id="k-selected-lang" value="ar">
        <input type="hidden" name="full_name" id="k-full-name-concat">
        <input type="hidden" name="id" value="<?php echo $resume_id; ?>">

        <div id="k-step-container" style="flex:1; display:flex; align-items:center; justify-content:center; padding:40px; box-sizing:border-box;">
            <!-- Sub-steps rendered here -->
            <div id="k-step-content" style="width:100%; max-width:800px; transform: translateY(0); transition: 0.3s opacity;">
                <!-- Inner fields -->
            </div>
        </div>

        <!-- Sticky Footer -->
        <div id="k-footer" style="padding:20px 60px; background:#fff; border-top:1px solid #f1f5f9; display:flex; justify-content:space-between; align-items:center; height: 90px; flex-shrink:0;">
            <button type="button" id="k-prev" onclick="prevKStep()" class="k-btn-secondary" style="display:none;"><?php echo Control_I18n::t('prev'); ?></button>
            <div style="flex:1;"></div>
            <button type="button" id="k-next" onclick="nextKStep()" class="k-btn-primary"><?php echo Control_I18n::t('next'); ?></button>
            <button type="submit" id="k-submit" style="display:none;" class="k-btn-primary"><?php echo Control_I18n::t('save'); ?></button>
        </div>
    </form>

    <div id="kiosk-success" style="display:none; flex:1; flex-direction:column; align-items:center; justify-content:center; padding:40px; text-align:center; background:#fff;">
        <div style="width:100px; height:100px; background:#ecfdf5; border-radius:50%; display:flex; align-items:center; justify-content:center; margin-bottom:30px; color:#10b981;">
            <span class="dashicons dashicons-yes-alt" style="font-size:60px; width:60px; height:60px;"></span>
        </div>
        <h1 style="font-weight:800; color:#065f46; font-size:2.2rem;" data-t="success_title"><?php echo Control_I18n::t('success_title'); ?></h1>
        <p style="font-size:1.2rem; color:#475569; margin-bottom:40px;" data-t="success_desc"><?php echo Control_I18n::t('success_desc'); ?></p>
        <button onclick="location.href='<?php echo home_url(); ?>'" class="k-btn-primary" style="padding:15px 60px;" data-t="finish_btn"><?php echo Control_I18n::t('finish_btn'); ?></button>
    </div>
</div>

<style>
#kiosk-app-root * { box-sizing: border-box; }
.lang-link { background:none; border:none; color:rgba(255,255,255,0.6); cursor:pointer; font-size:0.9rem; font-weight:700; transition: 0.3s; padding: 5px; }
.lang-link:hover, .lang-link.active { color: #fff; }
.k-dot { width: 10px; height: 10px; border-radius: 50%; background: rgba(255,255,255,0.2); transition: 0.4s; }
.k-dot.active { background: var(--control-accent); transform: scale(1.2); }
.k-dot.completed { background: #fff; opacity: 0.6; }

.k-btn-primary { background:var(--control-primary); color:#fff; border:none; padding:12px 40px; font-size:1rem; border-radius:12px; font-weight:800; cursor:pointer; transition: 0.3s; }
.k-btn-secondary { background:#f8fafc; color:#1e293b; border:1.5px solid #e2e8f0; padding:12px 40px; font-size:1rem; border-radius:12px; font-weight:800; cursor:pointer; }
.k-btn-primary:hover { opacity: 0.9; }

.wiz-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 25px; }
.wiz-field { margin-bottom: 5px; }
.wiz-field label { display: block; font-size: 0.85rem; font-weight: 800; color: #64748b; margin-bottom: 8px; text-transform: uppercase; }
.wiz-field input, .wiz-field select, .wiz-field textarea { width: 100%; padding: 14px 18px; border-radius: 12px; border: 2px solid #e2e8f0; font-size: 1rem; background:#fff; transition:0.3s; color: #1e293b; font-family: inherit; }
.wiz-field input:focus { border-color: var(--control-primary); outline:none; }

@media (max-width: 768px) {
    .wiz-grid { grid-template-columns: 1fr; gap: 15px; }
    #k-header { padding: 10px 20px; }
    #k-footer { padding: 15px 30px; }
    #k-step-container { padding: 20px; }
}
</style>

<script>
const kStrings = <?php echo json_encode($strings); ?>;
const isStaff = <?php echo $is_staff ? 'true' : 'false'; ?>;
const resumeData = <?php echo json_encode($resume_data); ?>;

// Comprehensive Step Tree for Unified Flow
const stepTree = [
    { id: '1.1', phase: 1, title: 'identity_basic', fields: ['name_first', 'name_second', 'name_last'] },
    { id: '1.2', phase: 1, title: 'dob_gender', fields: ['dob', 'gender'] },
    { id: '1.3', phase: 1, title: 'nationality_residence', fields: ['nationality', 'country_residence', 'city_residence', 'national_id'] },

    { id: '2.1', phase: 2, title: 'guardian_identity', fields: ['guardian_name', 'guardian_relationship', 'guardian_id'] },
    { id: '2.2', phase: 2, title: 'guardian_contact', fields: ['father_phone', 'email'] },
    { id: '2.3', phase: 2, title: 'address_emergency', fields: ['address', 'emergency_contact', 'blood_type'] },

    { id: '3.1', phase: 3, title: 'medical_history_prev', fields: ['diag_prev', 'diag_prev_details', 'prev_rehab_centers'] },
    { id: '3.2', phase: 3, title: 'medical_history_cond', fields: ['chronic_conditions', 'current_medications'] },
    { id: '3.3', phase: 3, title: 'medical_history_delay', fields: ['motor_delay', 'speech_delay', 'sleep_issues', 'feeding_issues'] },

    { id: '4.1', phase: 4, title: 'functional_social', fields: ['eval_attention', 'eval_name_response', 'eval_eye_contact', 'eval_social'] },
    { id: '4.2', phase: 4, title: 'functional_behavior', fields: ['eval_tantrums', 'eval_instructions', 'eval_activity_level'] },
    { id: '4.3', phase: 4, title: 'functional_skills', fields: ['eval_independence', 'eval_language', 'eval_anxiety', 'intake_reason'] }
];

if (isStaff) {
    stepTree.push(
        { id: '5.1', phase: 5, title: 'internal_analysis_1', fields: ['case_classification', 'priority_level', 'suggested_pathway'] },
        { id: '5.2', phase: 5, title: 'internal_analysis_2', fields: ['final_decision', 'temp_id', 'assigned_specialists', 'internal_notes'] },
        { id: '6.1', phase: 6, title: 'final_activation', fields: ['permanent_id', 'case_status', 'activate_account'] }
    );
}

let currentStepIdx = 0;

// Resume logic: If resumeData exists, we find the first empty phase or start at Phase 5
if (resumeData) {
    if (resumeData.intake_status === 'pending') {
        currentStepIdx = stepTree.findIndex(s => s.phase === 5);
    }
}

const optionData = {
    gender: { ar: [{v:'male', t:'ذكر'}, {v:'female', t:'أنثى'}], en: [{v:'male', t:'Male'}, {v:'female', t:'Female'}] },
    nationality: {
        ar: [{v:'SA', t:'السعودية'}, {v:'AE', t:'الإمارات'}, {v:'EG', t:'مصر'}, {v:'KW', t:'الكويت'}, {v:'QA', t:'قطر'}, {v:'BH', t:'البحرين'}, {v:'OM', t:'عمان'}, {v:'JO', t:'الأردن'}, {v:'other', t:'أخرى'}],
        en: [{v:'SA', t:'Saudi Arabia'}, {v:'AE', t:'UAE'}, {v:'EG', t:'Egypt'}, {v:'KW', t:'Kuwait'}, {v:'QA', t:'Qatar'}, {v:'BH', t:'Bahrain'}, {v:'OM', t:'Oman'}, {v:'JO', t:'Jordan'}, {v:'other', t:'Other'}]
    },
    relationship: {
        ar: [{v:'father', t:'الأب'}, {v:'mother', t:'الأم'}, {v:'relative', t:'قريب'}, {v:'legal', t:'ولي أمر شرعي'}],
        en: [{v:'father', t:'Father'}, {v:'mother', t:'Mother'}, {v:'relative', t:'Relative'}, {v:'legal', t:'Legal Guardian'}]
    },
    blood_type: { ar: [{v:'', t:'-'}, {v:'A+', t:'A+'}, {v:'A-', t:'A-'}, {v:'B+', t:'B+'}, {v:'B-', t:'B-'}, {v:'AB+', t:'AB+'}, {v:'AB-', t:'AB-'}, {v:'O+', t:'O+'}, {v:'O-', t:'O-'}], en: [{v:'', t:'-'}, {v:'A+', t:'A+'}, {v:'A-', t:'A-'}, {v:'B+', t:'B+'}, {v:'B-', t:'B-'}, {v:'AB+', t:'AB+'}, {v:'AB-', t:'AB-'}, {v:'O+', t:'O+'}, {v:'O-', t:'O-'}] },
    boolean: { ar: [{v:'no', t:'لا'}, {v:'yes', t:'نعم'}], en: [{v:'no', t:'No'}, {v:'yes', t:'Yes'}] },
    social: { ar: [{v:'positive', t:'جيد'}, {v:'limited', t:'متوسط'}, {v:'isolated', t:'ضعيف'}], en: [{v:'positive', t:'Good'}, {v:'limited', t:'Average'}, {v:'isolated', t:'Poor'}] },
    language: { ar: [{v:'non_verbal', t:'غير ناطق'}, {v:'words', t:'كلمات'}, {v:'sentences', t:'جمل'}], en: [{v:'non_verbal', t:'Non-verbal'}, {v:'words', t:'Words'}, {v:'sentences', t:'Sentences'}] },
    classification: { ar: [{v:'normal', t:'طبيعي'}, {v:'possible_delay', t:'تأخر محتمل'}, {v:'needs_evaluation', t:'يحتاج تقييم'}, {v:'needs_intervention', t:'يحتاج تدخل'}], en: [{v:'normal', t:'Normal'}, {v:'possible_delay', t:'Possible Delay'}, {v:'needs_evaluation', t:'Needs Evaluation'}, {v:'needs_intervention', t:'Needs Intervention'}] },
    priority: { ar: [{v:'normal', t:'عادي'}, {v:'urgent', t:'عاجل'}, {v:'critical', t:'حرج'}], en: [{v:'normal', t:'Normal'}, {v:'urgent', t:'Urgent'}, {v:'critical', t:'Critical'}] },
    pathway: { ar: [{v:'consultation', t:'استشارة'}, {v:'assessment', t:'تقييم'}, {v:'rehab_program', t:'برنامج تأهيلي'}], en: [{v:'consultation', t:'Consultation'}, {v:'assessment', t:'Assessment'}, {v:'rehab_program', t:'Rehabilitation Program'}] },
    decision: { ar: [{v:'pre_acceptance', t:'قبول مبدئي'}, {v:'rejected', t:'مرفوض'}, {v:'closed', t:'مغلق'}], en: [{v:'pre_acceptance', t:'Pre-acceptance'}, {v:'rejected', t:'Rejected'}, {v:'closed', t:'Closed'}] },
    status: { ar: [{v:'active', t:'نشط في النظام'}, {v:'waiting_list', t:'قائمة انتظار'}, {v:'completed', t:'تم التأهيل'}], en: [{v:'active', t:'Active in System'}, {v:'waiting_list', t:'Waiting List'}, {v:'completed', t:'Completed Rehabilitation'}] }
};

function renderStep() {
    const $ = jQuery;
    const step = stepTree[currentStepIdx];
    const lang = $('#k-selected-lang').val();
    const s = kStrings[lang];

    $('#k-step-content').css('opacity', 0);

    setTimeout(() => {
        let html = `<h2 style="color:var(--control-primary); font-weight:800; margin-bottom:35px; text-align:center;">${s[step.title] || step.title}</h2>`;
        html += `<div class="wiz-grid">`;

        step.fields.forEach(f => {
            const val = resumeData ? (resumeData[f] || '') : '';
            html += `<div class="wiz-field">`;
            html += `<label>${s[f] || f}</label>`;

            if (['gender', 'nationality', 'guardian_relationship', 'blood_type', 'diag_prev', 'prev_rehab_centers', 'motor_delay', 'speech_delay', 'sleep_issues', 'feeding_issues', 'eval_social', 'eval_language', 'case_classification', 'priority_level', 'suggested_pathway', 'final_decision', 'case_status'].includes(f)) {
                let source = f;
                if (['diag_prev', 'prev_rehab_centers', 'motor_delay', 'speech_delay', 'sleep_issues', 'feeding_issues'].includes(f)) source = 'boolean';
                if (f === 'eval_social') source = 'social';
                if (f === 'eval_language') source = 'language';
                if (f === 'guardian_relationship') source = 'relationship';
                if (f === 'case_classification') source = 'classification';
                if (f === 'priority_level') source = 'priority';
                if (f === 'suggested_pathway') source = 'pathway';
                if (f === 'final_decision') source = 'decision';
                if (f === 'case_status') source = 'status';

                html += `<select name="${f}">`;
                (optionData[source][lang] || []).forEach(opt => {
                    const selected = val == opt.v ? 'selected' : '';
                    html += `<option value="${opt.v}" ${selected}>${opt.t}</option>`;
                });
                html += `</select>`;
            } else if (['intake_reason', 'initial_behavioral_observation', 'initial_diagnosis', 'internal_notes', 'assigned_specialists'].includes(f)) {
                html += `<textarea name="${f}" rows="3">${val}</textarea>`;
            } else if (f === 'activate_account') {
                html += `<label style="display:flex; align-items:center; gap:10px; cursor:pointer; background:#f8fafc; padding:15px; border-radius:12px; border:2px solid #e2e8f0;">
                            <input type="checkbox" name="activate_account" value="1" ${val ? 'checked' : ''}>
                            <span style="font-size:0.9rem; color:var(--control-primary);">${s.account_activation}</span>
                         </label>`;
            } else {
                const type = f === 'dob' ? 'date' : (f === 'email' ? 'email' : (f === 'father_phone' ? 'tel' : 'text'));
                const required = ['name_first', 'name_second', 'name_last', 'dob', 'guardian_name', 'father_phone'].includes(f) ? 'required' : '';
                html += `<input type="${type}" name="${f}" value="${val}" ${required}>`;
            }
            html += `</div>`;
        });

        html += `</div>`;

        $('#k-step-content').html(html).css('opacity', 1);
        updateKUI();
    }, 150);
}

function nextKStep() {
    if (validateStep()) {
        if (currentStepIdx < stepTree.length - 1) {
            currentStepIdx++;
            renderStep();
        }
    }
}

function prevKStep() {
    if (currentStepIdx > 0) {
        currentStepIdx--;
        renderStep();
    }
}

function updateKUI() {
    const $ = jQuery;
    const lang = $('#k-selected-lang').val();
    const s = kStrings[lang];

    $('#k-prev').toggle(currentStepIdx > 0).text(s.prev);
    $('#k-next').toggle(currentStepIdx < stepTree.length - 1).text(s.next);
    $('#k-submit').toggle(currentStepIdx === stepTree.length - 1).text(s.save);

    // Generate Dots
    let dotsHtml = '';
    stepTree.forEach((step, idx) => {
        let status = '';
        if (idx === currentStepIdx) status = 'active';
        else if (idx < currentStepIdx) status = 'completed';
        dotsHtml += `<div class="k-dot ${status}" title="Step ${step.id}"></div>`;
    });
    $('#k-dots-container').html(dotsHtml);
}

function validateStep() {
    let valid = true;
    jQuery('#k-step-content [required]').each(function() {
        if (!jQuery(this).val()) { jQuery(this).css('border-color', '#ef4444'); valid = false; }
        else { jQuery(this).css('border-color', ''); }
    });
    return valid;
}

function setKLang(lang) {
    const $ = jQuery;
    $('#k-selected-lang').val(lang);
    $('.lang-link').removeClass('active');
    $(`#btn-${lang}`).addClass('active');
    $('#kiosk-app-root').css('direction', lang === 'ar' ? 'rtl' : 'ltr');
    renderStep();
}

jQuery(document).ready(function($) {
    setKLang('ar');

    $('#kiosk-form').on('submit', function(e) {
        e.preventDefault();
        const $btn = $('#k-submit'); $btn.prop('disabled', true).text('...');

        // Auto-concat full name
        const f = $('[name="name_first"]').val() || '';
        const s = $('[name="name_second"]').val() || '';
        const l = $('[name="name_last"]').val() || '';
        $('#k-full-name-concat').val(`${f} ${s} ${l}`.trim());

        $.post(control_ajax.ajax_url, $(this).serialize() + '&action=control_save_patient&nonce=' + control_ajax.nonce, (res) => {
            if (res.success) {
                $('#kiosk-form, #k-header').hide();
                $('#kiosk-success').css('display', 'flex');
            } else {
                alert(res.data);
                $btn.prop('disabled', false).text(kStrings[$('#k-selected-lang').val()].save);
            }
        });
    });
});
</script>
